version: '3.8'
services:
  cassandra:
    image: cassandra:latest
    container_name: chime-cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
      - "7000:7000"
    environment:
      - CASSANDRA_CLUSTER_NAME=chime_cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./cassandra/config:/etc/cassandra
    networks:
      - chime-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  cassandra_data:

networks:
  chime-network:
    driver: bridge
