[api]
host="localhost"
port=3142

[chat]
port=3143

[redis]
host="localhost"
port=6379
username="default"
password=

[redis.test]
host="localhost"
port=6380
password=

[cassandra]
host="localhost"
port=9042
